import { type AuthLocalization } from "@daveyplate/better-auth-ui";

const AuthLocalization_PT_BR = {
  INVALID_USERNAME_OR_PASSWORD: "Usuário ou senha inválidos",
  EMAIL_NOT_VERIFIED: "E-mail não verificado",
  UNEXPECTED_ERROR: "Ocorreu um erro inesperado",
  USERNAME_IS_ALREADY_TAKEN: "Este nome de usuário já está em uso",
  USERNAME_TOO_SHORT: "Nome de usuário muito curto",
  USERNAME_TOO_LONG: "Nome de usuário muito longo",
  INVALID_USERNAME: "Nome de usuário inválido",
  OTP_NOT_ENABLED: "OTP não habilitado",
  OTP_HAS_EXPIRED: "O código OTP expirou",
  TOTP_NOT_ENABLED: "TOTP não habilitado",
  TWO_FACTOR_NOT_ENABLED: "A autenticação de dois fatores não está habilitada",
  BACKUP_CODES_NOT_ENABLED: "Os códigos de backup não estão habilitados",
  INVALID_BACKUP_CODE: "Código de backup inválido",
  INVALID_CODE: "Código inválido",
  TOO_MANY_ATTEMPTS_REQUEST_NEW_CODE: "Muitas tentativas. Solicite um novo código.",
  INVALID_TWO_FACTOR_COOKIE: "Cookie de dois fatores inválido",
  TEAM_LIMIT_REACHED: "Limite de equipes atingido",
  TEAM_MEMBER_LIMIT_REACHED: "Limite de membros da equipe atingido",
  TEAM_NOT_FOUND: "Equipe não encontrada",
  TEAM_MEMBER_NOT_FOUND: "Membro da equipe não encontrado",
  TEAM_NAME_TOO_LONG: "Nome da equipe muito longo",
  CANNOT_REMOVE_LAST_TEAM: "Não é possível remover a última equipe",
  NOT_ORGANIZATION_MEMBER: "Você não é membro da organização",
  ALREADY_TEAM_MEMBER: "Este usuário já é membro da equipe",
  INSUFFICIENT_TEAM_PERMISSIONS: "Permissões insuficientes na equipe",
  SUBSCRIPTION_NOT_FOUND: "Assinatura não encontrada",
  SUBSCRIPTION_PLAN_NOT_FOUND: "Plano de assinatura não encontrado",
  ALREADY_SUBSCRIBED_PLAN: "Você já está inscrito neste plano",
  UNABLE_TO_CREATE_CUSTOMER: "Não foi possível criar o cliente",
  FAILED_TO_FETCH_PLANS: "Falha ao buscar os planos",
  EMAIL_VERIFICATION_REQUIRED: "Verificação de e-mail obrigatória",
  SUBSCRIPTION_NOT_ACTIVE: "Assinatura inativa",
  SUBSCRIPTION_NOT_SCHEDULED_FOR_CANCELLATION:
    "A assinatura não está agendada para cancelamento",
  INVALID_PHONE_NUMBER: "Número de telefone inválido",
  PHONE_NUMBER_EXIST: "Este número de telefone já existe",
  INVALID_PHONE_NUMBER_OR_PASSWORD: "Número de telefone ou senha inválidos",
  OTP_NOT_FOUND: "OTP não encontrado",
  OTP_EXPIRED: "OTP expirado",
  INVALID_OTP: "OTP inválido",
  PHONE_NUMBER_NOT_VERIFIED: "Número de telefone não verificado",
  CHALLENGE_NOT_FOUND: "Desafio não encontrado",
  YOU_ARE_NOT_ALLOWED_TO_REGISTER_THIS_PASSKEY:
    "Você não tem permissão para registrar esta passkey",
  FAILED_TO_VERIFY_REGISTRATION: "Falha ao verificar o registro",
  PASSKEY_NOT_FOUND: "Passkey não encontrada",
  AUTHENTICATION_FAILED: "Falha na autenticação",
  UNABLE_TO_CREATE_SESSION: "Não foi possível criar a sessão",
  FAILED_TO_UPDATE_PASSKEY: "Falha ao atualizar a passkey",
  YOU_ARE_NOT_ALLOWED_TO_CREATE_A_NEW_ORGANIZATION:
    "Você não tem permissão para criar uma nova organização",
  YOU_HAVE_REACHED_THE_MAXIMUM_NUMBER_OF_ORGANIZATIONS:
    "Você atingiu o número máximo de organizações",
  ORGANIZATION_ALREADY_EXISTS: "A organização já existe",
  ORGANIZATION_NOT_FOUND: "Organização não encontrada",
  USER_IS_NOT_A_MEMBER_OF_THE_ORGANIZATION:
    "O usuário não é membro da organização",
  YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_ORGANIZATION:
    "Você não tem permissão para atualizar esta organização",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_ORGANIZATION:
    "Você não tem permissão para excluir esta organização",
  NO_ACTIVE_ORGANIZATION: "Nenhuma organização ativa",
  USER_IS_ALREADY_A_MEMBER_OF_THIS_ORGANIZATION:
    "O usuário já é membro desta organização",
  MEMBER_NOT_FOUND: "Membro não encontrado",
  ROLE_NOT_FOUND: "Função não encontrada",
  YOU_ARE_NOT_ALLOWED_TO_CREATE_A_NEW_TEAM:
    "Você não tem permissão para criar uma nova equipe",
  TEAM_ALREADY_EXISTS: "A equipe já existe",
  YOU_CANNOT_LEAVE_THE_ORGANIZATION_AS_THE_ONLY_OWNER:
    "Você não pode sair da organização sendo o único proprietário",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_MEMBER:
    "Você não tem permissão para remover este membro",
  YOU_ARE_NOT_ALLOWED_TO_INVITE_USERS_TO_THIS_ORGANIZATION:
    "Você não tem permissão para convidar usuários para esta organização",
  USER_IS_ALREADY_INVITED_TO_THIS_ORGANIZATION:
    "O usuário já foi convidado para esta organização",
  INVITATION_NOT_FOUND: "Convite não encontrado",
  YOU_ARE_NOT_THE_RECIPIENT_OF_THE_INVITATION:
    "Você não é o destinatário deste convite",
  YOU_ARE_NOT_ALLOWED_TO_CANCEL_THIS_INVITATION:
    "Você não tem permissão para cancelar este convite",
  INVITER_IS_NO_LONGER_A_MEMBER_OF_THE_ORGANIZATION:
    "Quem convidou não é mais membro da organização",
  YOU_ARE_NOT_ALLOWED_TO_INVITE_USER_WITH_THIS_ROLE:
    "Você não tem permissão para convidar um usuário com esta função",
  FAILED_TO_RETRIEVE_INVITATION: "Falha ao recuperar o convite",
  YOU_HAVE_REACHED_THE_MAXIMUM_NUMBER_OF_TEAMS:
    "Você atingiu o número máximo de equipes",
  UNABLE_TO_REMOVE_LAST_TEAM: "Não foi possível remover a última equipe",
  YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_MEMBER:
    "Você não tem permissão para atualizar este membro",
  ORGANIZATION_MEMBERSHIP_LIMIT_REACHED: "Limite de membros da organização atingido",
  YOU_ARE_NOT_ALLOWED_TO_CREATE_TEAMS_IN_THIS_ORGANIZATION:
    "Você não tem permissão para criar equipes nesta organização",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_TEAMS_IN_THIS_ORGANIZATION:
    "Você não tem permissão para excluir equipes nesta organização",
  YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_TEAM:
    "Você não tem permissão para atualizar esta equipe",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_TEAM:
    "Você não tem permissão para excluir esta equipe",
  INVITATION_LIMIT_REACHED: "Limite de convites atingido",
  INVALID_SESSION_TOKEN: "Token de sessão inválido",
  PASSWORD_COMPROMISED: "Senha comprometida",
  INVALID_OAUTH_CONFIGURATION: "Configuração OAuth inválida",
  INVALID_EMAIL: "E-mail inválido",
  USER_NOT_FOUND: "Usuário não encontrado",
  TOO_MANY_ATTEMPTS: "Muitas tentativas. Tente novamente em alguns minutos.",
  MISSING_SECRET_KEY: "Chave secreta ausente",
  SERVICE_UNAVAILABLE: "Serviço indisponível",
  VERIFICATION_FAILED: "Falha na verificação",
  MISSING_RESPONSE: "Resposta ausente",
  UNKNOWN_ERROR: "Erro desconhecido",
  INVALID_METADATA_TYPE: "Tipo de metadado inválido",
  REFILL_AMOUNT_AND_INTERVAL_REQUIRED:
    "Valor de recarga e intervalo são obrigatórios",
  REFILL_INTERVAL_AND_AMOUNT_REQUIRED:
    "Intervalo de recarga e valor são obrigatórios",
  USER_BANNED: "Usuário banido",
  UNAUTHORIZED_SESSION: "Sessão não autorizada",
  KEY_NOT_FOUND: "Chave não encontrada",
  KEY_DISABLED: "Chave desativada",
  KEY_EXPIRED: "Chave expirada",
  USAGE_EXCEEDED: "Uso excedido",
  KEY_NOT_RECOVERABLE: "Chave não recuperável",
  EXPIRES_IN_IS_TOO_SMALL: "O valor de expiração é muito pequeno",
  EXPIRES_IN_IS_TOO_LARGE: "O valor de expiração é muito grande",
  INVALID_REMAINING: "Valor restante inválido",
  INVALID_PREFIX_LENGTH: "Comprimento de prefixo inválido",
  INVALID_NAME_LENGTH: "Comprimento de nome inválido",
  METADATA_DISABLED: "Metadados desativados",
  RATE_LIMIT_EXCEEDED: "Limite de taxa excedido",
  NO_VALUES_TO_UPDATE: "Não há valores para atualizar",
  KEY_DISABLED_EXPIRATION: "Expiração de chave desativada",
  INVALID_API_KEY: "Chave de API inválida",
  INVALID_USER_ID_FROM_API_KEY: "ID de usuário inválido a partir da chave de API",
  INVALID_API_KEY_GETTER_RETURN_TYPE:
    "Tipo de retorno inválido do recuperador de chave de API",
  SERVER_ONLY_PROPERTY: "Propriedade apenas do servidor",
  FAILED_TO_CREATE_USER: "Falha ao criar o usuário",
  COULD_NOT_CREATE_SESSION: "Não foi possível criar a sessão",
  ANONYMOUS_USERS_CANNOT_SIGN_IN_AGAIN_ANONYMOUSLY:
    "Usuários anônimos não podem entrar anonimamente novamente",
  USER_ALREADY_EXISTS: "Usuário já existe",
  YOU_CANNOT_BAN_YOURSELF: "Você não pode banir a si mesmo",
  YOU_ARE_NOT_ALLOWED_TO_CHANGE_USERS_ROLE:
    "Você não tem permissão para alterar a função dos usuários",
  YOU_ARE_NOT_ALLOWED_TO_CREATE_USERS:
    "Você não tem permissão para criar usuários",
  YOU_ARE_NOT_ALLOWED_TO_LIST_USERS: "Você não tem permissão para listar usuários",
  YOU_ARE_NOT_ALLOWED_TO_LIST_USERS_SESSIONS:
    "Você não tem permissão para listar sessões de usuários",
  YOU_ARE_NOT_ALLOWED_TO_BAN_USERS:
    "Você não tem permissão para banir usuários",
  YOU_ARE_NOT_ALLOWED_TO_IMPERSONATE_USERS:
    "Você não tem permissão para personificar usuários",
  YOU_ARE_NOT_ALLOWED_TO_REVOKE_USERS_SESSIONS:
    "Você não tem permissão para revogar sessões de usuários",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_USERS:
    "Você não tem permissão para excluir usuários",
  YOU_ARE_NOT_ALLOWED_TO_SET_USERS_PASSWORD:
    "Você não tem permissão para definir a senha dos usuários",
  BANNED_USER: "Usuário banido",
  FAILED_TO_CREATE_SESSION: "Falha ao criar sessão",
  FAILED_TO_UPDATE_USER: "Falha ao atualizar usuário",
  FAILED_TO_GET_SESSION: "Falha ao obter sessão",
  INVALID_PASSWORD: "Senha inválida",
  INVALID_EMAIL_OR_PASSWORD: "E-mail ou senha inválidos",
  SOCIAL_ACCOUNT_ALREADY_LINKED: "Conta social já vinculada",
  PROVIDER_NOT_FOUND: "Provedor não encontrado",
  INVALID_TOKEN: "Token inválido",
  ID_TOKEN_NOT_SUPPORTED: "ID token não suportado",
  FAILED_TO_GET_USER_INFO: "Falha ao obter informações do usuário",
  USER_EMAIL_NOT_FOUND: "E-mail do usuário não encontrado",
  PASSWORD_TOO_SHORT: "Senha muito curta",
  PASSWORD_TOO_LONG: "Senha muito longa",
  EMAIL_CAN_NOT_BE_UPDATED: "O e-mail não pode ser atualizado",
  CREDENTIAL_ACCOUNT_NOT_FOUND: "Conta de credencial não encontrada",
  SESSION_EXPIRED: "Sessão expirada",
  FAILED_TO_UNLINK_LAST_ACCOUNT: "Falha ao desvincular a última conta",
  ACCOUNT_NOT_FOUND: "Conta não encontrada",
  USER_ALREADY_HAS_PASSWORD: "O usuário já possui senha",
  APP: "Aplicativo",
  ACCOUNT: "Conta",
  ACCOUNTS: "Contas",
  ACCOUNTS_DESCRIPTION: "Gerencie as contas em que você está conectado atualmente.",
  ACCOUNTS_INSTRUCTIONS: "Entre em uma conta adicional.",
  ADD_ACCOUNT: "Adicionar conta",
  ADD_PASSKEY: "Adicionar passkey",
  ALREADY_HAVE_AN_ACCOUNT: "Já tem uma conta?",
  AVATAR: "Avatar",
  AVATAR_DESCRIPTION:
    "Clique no avatar para enviar uma imagem personalizada dos seus arquivos.",
  AVATAR_INSTRUCTIONS: "Um avatar é opcional, mas altamente recomendado.",
  BACKUP_CODE_REQUIRED: "Código de backup é obrigatório",
  BACKUP_CODES: "Códigos de backup",
  BACKUP_CODES_DESCRIPTION:
    "Salve estes códigos de backup em um local seguro. Você pode usá-los para acessar sua conta se perder seu método de autenticação de dois fatores.",
  BACKUP_CODE_PLACEHOLDER: "Código de backup.",
  BACKUP_CODE: "Código de backup",
  CANCEL: "Cancelar",
  CHANGE_PASSWORD: "Alterar senha",
  CHANGE_PASSWORD_DESCRIPTION: "Digite sua senha atual e uma nova senha.",
  CHANGE_PASSWORD_INSTRUCTIONS: "Use no mínimo 8 caracteres.",
  CHANGE_PASSWORD_SUCCESS: "Sua senha foi alterada.",
  CONFIRM_PASSWORD: "Confirmar senha",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirmar senha",
  CONFIRM_PASSWORD_REQUIRED: "A confirmação de senha é obrigatória",
  CONTINUE: "Continuar",
  CONTINUE_WITH_AUTHENTICATOR: "Continuar com autenticador",
  COPIED_TO_CLIPBOARD: "Copiado para a área de transferência",
  COPY_TO_CLIPBOARD: "Copiar para a área de transferência",
  COPY_ALL_CODES: "Copiar todos os códigos",
  CURRENT_PASSWORD: "Senha atual",
  CURRENT_PASSWORD_PLACEHOLDER: "Senha atual",
  CURRENT_SESSION: "Sessão atual",
  DELETE: "Excluir",
  DELETE_AVATAR: "Excluir avatar",
  DELETE_ACCOUNT: "Excluir conta",
  DELETE_ACCOUNT_DESCRIPTION:
    "Remova permanentemente sua conta e todo o seu conteúdo. Esta ação não é reversível, então prossiga com cautela.",
  DELETE_ACCOUNT_INSTRUCTIONS:
    "Confirme a exclusão da sua conta. Esta ação não é reversível, então prossiga com cautela.",
  DELETE_ACCOUNT_VERIFY:
    "Verifique seu e-mail para confirmar a exclusão da sua conta.",
  DELETE_ACCOUNT_SUCCESS: "Sua conta foi excluída.",
  DISABLE_TWO_FACTOR: "Desativar autenticação de dois fatores",
  DISABLED_CREDENTIALS_DESCRIPTION:
    "Escolha um provedor para entrar na sua conta",
  DONT_HAVE_AN_ACCOUNT: "Não tem uma conta?",
  DONE: "Concluído",
  EMAIL: "E-mail",
  EMAIL_DESCRIPTION: "Digite o e-mail que você deseja usar para entrar.",
  EMAIL_INSTRUCTIONS: "Digite um endereço de e-mail válido.",
  EMAIL_IS_THE_SAME: "O e-mail é o mesmo",
  EMAIL_PLACEHOLDER: "nome@exemplo.com",
  EMAIL_REQUIRED: "O e-mail é obrigatório",
  EMAIL_VERIFY_CHANGE: "Verifique seu e-mail para confirmar a alteração.",
  EMAIL_VERIFICATION: "Verificação de e-mail",
  EMAIL_VERIFICATION_DESCRIPTION:
    "Verifique seu e-mail para ver o código de confirmação e concluir seu cadastro.",
  EMAIL_VERIFICATION_SUCCESS: "Verificação de e-mail concluída.",
  ENABLE_TWO_FACTOR: "Ativar autenticação de dois fatores",
  IS_INVALID: "é inválido",
  IS_REQUIRED: "é obrigatório",
  IS_THE_SAME: "é o mesmo",
  FORGOT_AUTHENTICATOR: "Esqueceu o autenticador?",
  FORGOT_PASSWORD: "Esqueceu a senha?",
  FORGOT_PASSWORD_ACTION: "Enviar link de redefinição",
  FORGOT_PASSWORD_DESCRIPTION: "Digite seu e-mail para redefinir sua senha",
  FORGOT_PASSWORD_EMAIL:
    "Verifique seu e-mail para o link de redefinição de senha.",
  FORGOT_PASSWORD_LINK: "Esqueceu sua senha?",
  LINK: "Link",
  GO_BACK: "Voltar",
  MAGIC_LINK: "Link mágico",
  MAGIC_LINK_ACTION: "Enviar link mágico",
  MAGIC_LINK_DESCRIPTION: "Digite seu e-mail para receber um link mágico",
  MAGIC_LINK_EMAIL: "Verifique seu e-mail para o link mágico",
  EMAIL_OTP: "Código por e-mail",
  EMAIL_OTP_SEND_ACTION: "Enviar código",
  EMAIL_OTP_VERIFY_ACTION: "Verificar código",
  EMAIL_OTP_DESCRIPTION: "Digite seu e-mail para receber um código",
  EMAIL_OTP_VERIFICATION_SENT:
    "Verifique seu e-mail para encontrar o código de verificação.",
  NAME: "Nome",
  NAME_DESCRIPTION: "Digite seu nome completo ou um nome de exibição.",
  NAME_INSTRUCTIONS: "Use no máximo 32 caracteres.",
  NAME_PLACEHOLDER: "Nome",
  NEW_PASSWORD: "Nova senha",
  NEW_PASSWORD_PLACEHOLDER: "Nova senha",
  NEW_PASSWORD_REQUIRED: "A nova senha é obrigatória",
  ONE_TIME_PASSWORD: "Senha de uso único",
  OR_CONTINUE_WITH: "Ou continue com",
  PASSKEY: "Passkey",
  PASSKEYS: "Passkeys",
  PASSKEYS_DESCRIPTION: "Gerencie suas passkeys para acesso seguro.",
  PASSKEYS_INSTRUCTIONS: "Acesse sua conta com segurança, sem senha.",
  PERSONAL_ACCOUNT: "Conta pessoal",
  API_KEYS: "Chaves de API",
  API_KEYS_DESCRIPTION: "Gerencie suas chaves de API para acesso seguro.",
  API_KEYS_INSTRUCTIONS:
    "Gere chaves de API para acessar sua conta programaticamente.",
  CREATE_API_KEY: "Criar chave de API",
  CREATE_API_KEY_DESCRIPTION:
    "Digite um nome único para sua chave de API para diferenciá-la das outras.",
  API_KEY_NAME_PLACEHOLDER: "Nova chave de API",
  API_KEY_CREATED: "Chave de API criada",
  CREATE_API_KEY_SUCCESS:
    "Copie sua chave de API e salve em local seguro. Por segurança, não poderemos exibí-la novamente.",
  NEVER_EXPIRES: "Nunca expira",
  EXPIRES: "Expira",
  NO_EXPIRATION: "Sem expiração",
  CREATE_ORGANIZATION: "Criar organização",
  ORGANIZATION: "Organização",
  ORGANIZATION_NAME: "Nome",
  ORGANIZATION_NAME_PLACEHOLDER: "Acme Inc.",
  ORGANIZATION_NAME_DESCRIPTION: "Este é o nome visível da sua organização.",
  ORGANIZATION_NAME_INSTRUCTIONS: "Use no máximo 32 caracteres.",
  ORGANIZATION_SLUG: "Slug de URL",
  ORGANIZATION_SLUG_DESCRIPTION: "Este é o namespace de URL da sua organização.",
  ORGANIZATION_SLUG_INSTRUCTIONS: "Use no máximo 48 caracteres.",
  ORGANIZATION_SLUG_PLACEHOLDER: "acme-inc",
  CREATE_ORGANIZATION_SUCCESS: "Organização criada com sucesso",
  PASSWORD: "Senha",
  PASSWORD_PLACEHOLDER: "Senha",
  PASSWORD_REQUIRED: "A senha é obrigatória",
  PASSWORDS_DO_NOT_MATCH: "As senhas não coincidem",
  PROVIDERS: "Provedores",
  PROVIDERS_DESCRIPTION: "Conecte sua conta a um serviço de terceiros.",
  RECOVER_ACCOUNT: "Recuperar conta",
  RECOVER_ACCOUNT_ACTION: "Recuperar conta",
  RECOVER_ACCOUNT_DESCRIPTION:
    "Digite um código de backup para acessar sua conta",
  REMEMBER_ME: "Lembrar de mim",
  RESEND_CODE: "Reenviar código",
  RESEND_VERIFICATION_EMAIL: "Reenviar e-mail de verificação",
  RESET_PASSWORD: "Redefinir senha",
  RESET_PASSWORD_ACTION: "Salvar nova senha",
  RESET_PASSWORD_DESCRIPTION: "Digite sua nova senha abaixo",
  RESET_PASSWORD_SUCCESS: "Senha redefinida com sucesso",
  REQUEST_FAILED: "Falha na requisição",
  REVOKE: "Revogar",
  DELETE_API_KEY: "Excluir chave de API",
  DELETE_API_KEY_CONFIRM:
    "Tem certeza de que deseja excluir esta chave de API?",
  API_KEY: "Chave de API",
  SAVE: "Salvar",
  SETTINGS: "Configurações",
  SIGN_IN: "Entrar",
  SIGN_IN_ACTION: "Entrar",
  SIGN_IN_DESCRIPTION: "Digite seu e-mail abaixo para entrar na sua conta",
  SIGN_IN_USERNAME_DESCRIPTION:
    "Digite seu nome de usuário ou e-mail abaixo para entrar na sua conta",
  SIGN_IN_WITH: "Entrar com",
  SIGN_OUT: "Sair",
  SIGN_UP: "Criar conta",
  SIGN_UP_ACTION: "Criar uma conta",
  SIGN_UP_DESCRIPTION: "Digite seus dados para criar uma conta",
  SIGN_UP_EMAIL: "Verifique seu e-mail para o link de verificação.",
  SESSIONS: "Sessões",
  SESSIONS_DESCRIPTION: "Gerencie suas sessões ativas e revogue acessos.",
  SET_PASSWORD: "Definir senha",
  SET_PASSWORD_DESCRIPTION:
    "Clique no botão abaixo para receber um e-mail e definir uma senha para sua conta.",
  SECURITY: "Segurança",
  SWITCH_ACCOUNT: "Trocar conta",
  TRUST_DEVICE: "Confiar neste dispositivo",
  TWO_FACTOR: "Autenticação de dois fatores",
  TWO_FACTOR_ACTION: "Verificar código",
  TWO_FACTOR_DESCRIPTION: "Digite seu código de uso único para continuar",
  TWO_FACTOR_CARD_DESCRIPTION:
    "Adicione uma camada extra de segurança à sua conta.",
  TWO_FACTOR_DISABLE_INSTRUCTIONS: "Digite sua senha para desativar 2FA.",
  TWO_FACTOR_ENABLE_INSTRUCTIONS: "Digite sua senha para ativar 2FA.",
  TWO_FACTOR_ENABLED: "A autenticação de dois fatores foi ativada",
  TWO_FACTOR_DISABLED: "A autenticação de dois fatores foi desativada",
  TWO_FACTOR_PROMPT: "Autenticação de dois fatores",
  TWO_FACTOR_TOTP_LABEL: "Escaneie o QR Code com seu autenticador",
  SEND_VERIFICATION_CODE: "Enviar código de verificação",
  UNLINK: "Desvincular",
  UPDATED_SUCCESSFULLY: "Atualizado com sucesso",
  UPDATE: "Atualizar",
  USERNAME: "Nome de usuário",
  USERNAME_DESCRIPTION:
    "Digite o nome de usuário que você deseja usar para entrar.",
  USERNAME_INSTRUCTIONS: "Use no máximo 32 caracteres.",
  USERNAME_PLACEHOLDER: "Nome de usuário",
  OPTIONAL_BRACKETS: "(Opcional)",
  SIGN_IN_USERNAME_PLACEHOLDER: "Nome de usuário ou e-mail",
  VERIFY_YOUR_EMAIL: "Verifique seu e-mail",
  VERIFY_YOUR_EMAIL_DESCRIPTION:
    "Verifique seu endereço de e-mail. Confira sua caixa de entrada e, se não recebeu, reenvie o e-mail de verificação.",
  SESSION_NOT_FRESH: "Sua sessão não é recente. Entre novamente.",
  UPLOAD_AVATAR: "Enviar avatar",
  LOGO: "Logo",
  LOGO_DESCRIPTION:
    "Clique no logo para enviar uma imagem personalizada dos seus arquivos.",
  LOGO_INSTRUCTIONS: "Um logo é opcional, mas altamente recomendado.",
  UPLOAD: "Enviar",
  UPLOAD_LOGO: "Enviar logo",
  DELETE_LOGO: "Excluir logo",
  PRIVACY_POLICY: "Política de Privacidade",
  TERMS_OF_SERVICE: "Termos de Serviço",
  PROTECTED_BY_RECAPTCHA: "Este site é protegido por reCAPTCHA.",
  BY_CONTINUING_YOU_AGREE: "Ao continuar, você concorda com",
  USER: "Usuário",
  ORGANIZATIONS: "Organizações",
  ORGANIZATIONS_DESCRIPTION: "Gerencie suas organizações e participações.",
  ORGANIZATIONS_INSTRUCTIONS:
    "Crie uma organização para colaborar com outros usuários.",
  LEAVE_ORGANIZATION: "Sair da organização",
  LEAVE_ORGANIZATION_CONFIRM:
    "Tem certeza de que deseja sair desta organização?",
  LEAVE_ORGANIZATION_SUCCESS: "Você saiu da organização com sucesso.",
  MANAGE_ORGANIZATION: "Gerenciar organização",
  REMOVE_MEMBER: "Remover membro",
  REMOVE_MEMBER_CONFIRM:
    "Tem certeza de que deseja remover este membro da organização?",
  REMOVE_MEMBER_SUCCESS: "Membro removido com sucesso",
  INVITE_MEMBER: "Convidar membro",
  MEMBERS: "Membros",
  MEMBERS_DESCRIPTION: "Adicione ou remova membros e gerencie suas funções.",
  MEMBERS_INSTRUCTIONS: "Convide novos membros para sua organização.",
  INVITE_MEMBER_DESCRIPTION:
    "Envie um convite para adicionar um novo membro à sua organização.",
  ROLE: "Função",
  SELECT_ROLE: "Selecione uma função",
  ADMIN: "Administrador",
  MEMBER: "Membro",
  GUEST: "Convidado",
  OWNER: "Proprietário",
  UPDATE_ROLE_DESCRIPTION: "Atualize a função deste membro",
  UPDATE_ROLE: "Atualizar função",
  MEMBER_ROLE_UPDATED: "Função do membro atualizada com sucesso",
  SEND_INVITATION: "Enviar convite",
  SEND_INVITATION_SUCCESS: "Convite enviado com sucesso",
  PENDING_INVITATIONS: "Convites pendentes",
  PENDING_INVITATIONS_DESCRIPTION:
    "Gerencie os convites pendentes da sua organização.",
  PENDING_USER_INVITATIONS_DESCRIPTION:
    "Convites que você recebeu de organizações.",
  CANCEL_INVITATION: "Cancelar convite",
  INVITATION_CANCELLED: "Convite cancelado com sucesso",
  ACCEPT_INVITATION: "Aceitar convite",
  ACCEPT_INVITATION_DESCRIPTION:
    "Você foi convidado para entrar em uma organização.",
  INVITATION_ACCEPTED: "Convite aceito com sucesso",
  INVITATION_REJECTED: "Convite recusado com sucesso",
  ACCEPT: "Aceitar",
  REJECT: "Recusar",
  INVITATION_EXPIRED: "Este convite expirou",
  DELETE_ORGANIZATION: "Excluir organização",
  DELETE_ORGANIZATION_DESCRIPTION:
    "Remova permanentemente sua organização e todo o conteúdo dela. Esta ação não é reversível, então prossiga com cautela.",
  DELETE_ORGANIZATION_SUCCESS: "Organização excluída com sucesso",
  DELETE_ORGANIZATION_INSTRUCTIONS:
    "Digite o slug da organização para continuar:",
  SLUG_REQUIRED: "O slug da organização é obrigatório",
  SLUG_DOES_NOT_MATCH: "O slug não corresponde",
  TEAM: "Equipe",
  TEAMS: "Equipes",
  TEAM_ACTIVE: "Ativa",
  TEAM_SET_ACTIVE: "Definir como ativa",
  CREATE_TEAM: "Criar equipe",
  CREATE_TEAM_SUCCESS: "Equipe criada com sucesso",
  UPDATE_TEAM: "Atualizar equipe",
  UPDATE_TEAMS: "Atualizar equipes",
  SELECT_TEAMS: "Selecionar equipes",
  ADD: "Adicionar",
  REMOVE: "Remover",
  UPDATE_TEAM_DESCRIPTION: "Atualize o nome desta equipe",
  UPDATE_TEAMS_DESCRIPTION: "Adicione ou remova equipes para este membro",
  REMOVE_TEAM_CONFIRM:
    "Tem certeza de que deseja remover esta equipe da organização?",
  CREATE_TEAM_INSTRUCTIONS: "Adicione uma nova equipe à sua organização.",
  TEAM_NAME: "Nome da equipe",
  TEAM_NAME_PLACEHOLDER: "Equipe de Engenharia",
  TEAM_NAME_DESCRIPTION: "Este é o nome visível da sua equipe.",
  TEAM_NAME_INSTRUCTIONS: "Use no máximo 64 caracteres.",
  TEAMS_DESCRIPTION: "Gerencie suas equipes dentro da organização.",
  USER_TEAMS_DESCRIPTION: "Você é membro das seguintes equipes.",
  DELETE_TEAM: "Excluir equipe",
  DELETE_TEAM_DESCRIPTION:
    "Remova permanentemente esta equipe e todo o conteúdo dela.",
  DELETE_TEAM_SUCCESS: "Equipe excluída com sucesso",
  DELETE_TEAM_INSTRUCTIONS: "Digite o nome da equipe para continuar:",
  TEAM_NAME_REQUIRED: "O nome da equipe é obrigatório",
  TEAM_NAME_DOES_NOT_MATCH: "O nome da equipe não corresponde",
  TEAM_MEMBERS: "Membros da equipe",
  TEAM_MEMBERS_DESCRIPTION: "Gerencie os membros da equipe e suas funções.",
  ADD_TEAM_MEMBER: "Adicionar membro da equipe",
  REMOVE_TEAM_MEMBER: "Remover membro da equipe",
  REMOVE_TEAM_MEMBER_CONFIRM:
    "Tem certeza de que deseja remover este membro da equipe?",
  REMOVE_TEAM_MEMBER_SUCCESS: "Membro da equipe removido com sucesso",
  ADD_TEAM_MEMBER_SUCCESS: "Membro adicionado à equipe com sucesso",
  UPDATE_TEAM_SUCCESS: "Equipe atualizada com sucesso",
  MANAGE_TEAM_MEMBERS: "Gerenciar membros da equipe",
  MANAGE_TEAM_MEMBERS_DESCRIPTION:
    "Pesquise e adicione membros da organização a esta equipe.",
  NO_TEAMS_FOUND: "Nenhuma equipe encontrada",
  MEMBER_SINGULAR: "membro",
  MEMBER_PLURAL: "membros",
  UNKNOWN: "Desconhecido",
} satisfies AuthLocalization;

export default AuthLocalization_PT_BR;
