import { v } from "convex/values";

// Country codes according to ISO 3166-1 alpha-2.

const countryCodes = [
  "AF",
  "AX",
  "AL",
  "DZ",
  "AS",
  "AD",
  "AO",
  "AI",
  "AQ",
  "AG",
  "AR",
  "AM",
  "AW",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BM",
  "BT",
  "BO",
  "BQ",
  "BA",
  "BW",
  "BV",
  "BR",
  "IO",
  "BN",
  "BG",
  "BF",
  "BI",
  "CV",
  "KH",
  "CM",
  "CA",
  "KY",
  "CF",
  "TD",
  "CL",
  "CN",
  "CX",
  "CC",
  "CO",
  "KM",
  "CG",
  "CD",
  "CK",
  "CR",
  "CI",
  "HR",
  "CU",
  "CW",
  "CY",
  "CZ",
  "DK",
  "DJ",
  "DM",
  "DO",
  "EC",
  "EG",
  "SV",
  "GQ",
  "ER",
  "EE",
  "SZ",
  "ET",
  "FK",
  "FO",
  "FJ",
  "FI",
  "FR",
  "GF",
  "PF",
  "TF",
  "GA",
  "GM",
  "GE",
  "DE",
  "GH",
  "GI",
  "GR",
  "GL",
  "GD",
  "GP",
  "GU",
  "GT",
  "GG",
  "GN",
  "GW",
  "GY",
  "HT",
  "HM",
  "VA",
  "HN",
  "HK",
  "HU",
  "IS",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IM",
  "IL",
  "IT",
  "JM",
  "JP",
  "JE",
  "JO",
  "KZ",
  "KE",
  "KI",
  "KP",
  "KR",
  "KW",
  "KG",
  "LA",
  "LV",
  "LB",
  "LS",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MO",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MH",
  "MQ",
  "MR",
  "MU",
  "YT",
  "MX",
  "FM",
  "MD",
  "MC",
  "MN",
  "ME",
  "MS",
  "MA",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NL",
  "NC",
  "NZ",
  "NI",
  "NE",
  "NG",
  "NU",
  "NF",
  "MK",
  "MP",
  "NO",
  "OM",
  "PK",
  "PW",
  "PS",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PN",
  "PL",
  "PT",
  "PR",
  "QA",
  "RE",
  "RO",
  "RU",
  "RW",
  "BL",
  "SH",
  "KN",
  "LC",
  "MF",
  "PM",
  "VC",
  "WS",
  "SM",
  "ST",
  "SA",
  "SN",
  "RS",
  "SC",
  "SL",
  "SG",
  "SX",
  "SK",
  "SI",
  "SB",
  "SO",
  "ZA",
  "GS",
  "SS",
  "ES",
  "LK",
  "SD",
  "SR",
  "SJ",
  "SE",
  "CH",
  "SY",
  "TW",
  "TJ",
  "TZ",
  "TH",
  "TL",
  "TG",
  "TK",
  "TO",
  "TT",
  "TN",
  "TR",
  "TM",
  "TC",
  "TV",
  "UG",
  "UA",
  "AE",
  "GB",
  "US",
  "UM",
  "UY",
  "UZ",
  "VU",
  "VE",
  "VN",
  "VG",
  "VI",
  "WF",
  "EH",
  "YE",
  "ZM",
  "ZW",
] as const;

export type CountryCode = (typeof countryCodes)[number];

export type Country = {
  code: CountryCode;
  name: string;
  fullName: string;
};

const fullCountryNames: Partial<Record<CountryCode, string>> = {
  AF: "República Islâmica do Afeganistão",
  AL: "República da Albânia",
  DZ: "República Democrática Popular da Argélia",
  AD: "Principado de Andorra",
  AO: "República de Angola",
  AR: "República Argentina",
  AM: "República da Armênia",
  AU: "Comunidade da Austrália",
  AT: "República da Áustria",
  AZ: "República do Azerbaijão",
  BH: "Reino do Barein",
  BD: "República Popular de Bangladesh",
  BY: "República da Bielorrússia",
  BE: "Reino da Bélgica",
  BJ: "República do Benin",
  BT: "Reino do Butão",
  BO: "Estado Plurinacional da Bolívia",
  BW: "República do Botsuana",
  BR: "República Federativa do Brasil",
  BG: "República da Bulgária",
  BI: "República do Burundi",
  CV: "República de Cabo Verde",
  KH: "Reino do Camboja",
  CM: "República dos Camarões",
  TD: "República do Chade",
  CL: "República do Chile",
  CN: "República Popular da China",
  CO: "República da Colômbia",
  KM: "União das Comores",
  CG: "República do Congo",
  CD: "República Democrática do Congo",
  CR: "República da Costa Rica",
  CI: "República da Costa do Marfim",
  HR: "República da Croácia",
  CU: "República de Cuba",
  CY: "República de Chipre",
  CZ: "República Tcheca",
  DK: "Reino da Dinamarca",
  DJ: "República do Djibuti",
  DO: "República Dominicana",
  EC: "República do Equador",
  EG: "República Árabe do Egito",
  SV: "República de El Salvador",
  GQ: "República da Guiné Equatorial",
  EE: "República da Estônia",
  SZ: "Reino de Essuatíni",
  ET: "República Democrática Federal da Etiópia",
  FJ: "República de Fiji",
  FI: "República da Finlândia",
  FR: "República Francesa",
  GA: "República Gabonesa",
  GM: "República da Gâmbia",
  DE: "República Federal da Alemanha",
  GH: "República de Gana",
  GR: "República Helênica",
  GT: "República da Guatemala",
  GN: "República da Guiné",
  GW: "República da Guiné-Bissau",
  GY: "República Cooperativa da Guiana",
  HT: "República do Haiti",
  VA: "Santa Sé",
  HN: "República de Honduras",
  IN: "República da Índia",
  ID: "República da Indonésia",
  IR: "República Islâmica do Irã",
  IQ: "República do Iraque",
  IL: "Estado de Israel",
  IT: "República Italiana",
  JO: "Reino Hachemita da Jordânia",
  KZ: "República do Cazaquistão",
  KE: "República do Quênia",
  KI: "República de Quiribati",
  KP: "República Popular Democrática da Coreia",
  KR: "República da Coreia",
  KW: "Estado do Kuwait",
  KG: "República do Quirguistão",
  LA: "República Democrática Popular do Laos",
  LV: "República da Letônia",
  LB: "República Libanesa",
  LS: "Reino do Lesoto",
  LR: "República da Libéria",
  LY: "Estado da Líbia",
  LI: "Principado de Liechtenstein",
  LT: "República da Lituânia",
  LU: "Grão-Ducado de Luxemburgo",
  MG: "República de Madagascar",
  MW: "República do Malaui",
  MV: "República das Maldivas",
  ML: "República do Mali",
  MT: "República de Malta",
  MH: "República das Ilhas Marshall",
  MR: "República Islâmica da Mauritânia",
  MU: "República de Maurício",
  MX: "Estados Unidos Mexicanos",
  FM: "Estados Federados da Micronésia",
  MD: "República da Moldávia",
  MC: "Principado de Mônaco",
  MA: "Reino do Marrocos",
  MZ: "República de Moçambique",
  MM: "República da União de Mianmar",
  NA: "República da Namíbia",
  NR: "República de Nauru",
  NP: "República Federal Democrática do Nepal",
  NL: "Reino dos Países Baixos",
  NI: "República da Nicarágua",
  NE: "República do Níger",
  NG: "República Federal da Nigéria",
  NO: "Reino da Noruega",
  OM: "Sultanato de Omã",
  PK: "República Islâmica do Paquistão",
  PW: "República de Palau",
  PS: "Estado da Palestina",
  PA: "República do Panamá",
  PG: "Estado Independente de Papua-Nova Guiné",
  PY: "República do Paraguai",
  PE: "República do Peru",
  PH: "República das Filipinas",
  PL: "República da Polônia",
  PT: "República Portuguesa",
  QA: "Estado do Catar",
  RU: "Federação Russa",
  RW: "República de Ruanda",
  ST: "República Democrática de São Tomé e Príncipe",
  SA: "Reino da Arábia Saudita",
  SN: "República do Senegal",
  RS: "República da Sérvia",
  SC: "República das Seicheles",
  SL: "República da Serra Leoa",
  SG: "República de Singapura",
  SK: "República Eslovaca",
  SI: "República da Eslovênia",
  SO: "República Federal da Somália",
  ZA: "República da África do Sul",
  SS: "República do Sudão do Sul",
  ES: "Reino da Espanha",
  LK: "República Democrática Socialista do Sri Lanka",
  SD: "República do Sudão",
  SR: "República do Suriname",
  SE: "Reino da Suécia",
  CH: "Confederação Suíça",
  SY: "República Árabe Síria",
  TJ: "República do Tadjiquistão",
  TZ: "República Unida da Tanzânia",
  TH: "Reino da Tailândia",
  TL: "República Democrática de Timor-Leste",
  TG: "República Togolesa",
  TO: "Reino de Tonga",
  TT: "República de Trinidad e Tobago",
  TN: "República da Tunísia",
  TR: "República da Turquia",
  UG: "República de Uganda",
  GB: "Reino Unido da Grã-Bretanha e Irlanda do Norte",
  US: "Estados Unidos da América",
  UY: "República Oriental do Uruguai",
  UZ: "República do Uzbequistão",
  VU: "República de Vanuatu",
  VE: "República Bolivariana da Venezuela",
  VN: "República Socialista do Vietnã",
  YE: "República do Iêmen",
  ZM: "República da Zâmbia",
  ZW: "República do Zimbábue",
};

const countryDisplayNames = new Intl.DisplayNames(["pt-BR"], {
  type: "region",
});

function getCountryName(code: CountryCode) {
  return countryDisplayNames.of(code) ?? code;
}

function createCountry(code: CountryCode): Country {
  const name = getCountryName(code);

  return {
    code,
    name,
    fullName: fullCountryNames[code] ?? name,
  };
}

export const countries: Country[] = countryCodes.map(createCountry);

export default countries;

export const countriesConvexSchema = v.union(
  ...countryCodes.map((code) => v.literal(code)),
);

export function countryCodeToFlagUrl(code: string): string | null {
  if (code.length !== 2) {
    return null;
  }

  return `https://flagcdn.com/${code.toLowerCase()}.svg`;
}

export function getCountryByCode(code: string): Country | undefined {
  return countries.find((country) => country.code === code);
}
